### ISSUE TITLE
I can not login

### ISSUE THREAD

**Issue by richard-ma** [freefcw/hustoj#47]
之前用旧版的hustoj一直很正常，今天下了新的web包，填写好数据库信息后发现题目信息和比赛什么都可以正常显示了。问题是登录不正常，每次填写正确的用户名和密码后，没有任何提示就跳转到主页了。然后导航栏不能显示用户名，还显示login。用旧版本的登录正常。
注：新旧版本共用同一个数据库，而且judge端用的是数据库同步，没有开启http_judge

**Comment by dotkrnl** [comment]
其实好久没维护都忘了可能的原因了 = =
`application/config/base.php` 配置是否正常

**Comment by freefcw** [comment]
你可以试试跟踪一下源代码，没有任何信息我这也没有办法查看具体的问题
