### ISSUE TITLE
It stopped on this pending results

### ISSUE THREAD

**Issue by bluebild** [freefcw/hustoj#49]
Help me!!

Press the Submit button , the results continue to stop the pending.

Press the Status menu was refreshing . The result is still continuing pending .

**Comment by dotkrnl** [comment]
Original HUSTOJ backend must be configured properly. Please check that you have installed judged and the database settings of judged is correct.

**Comment by kaichengyan** [comment]
Results are always pending on the new hustoj ("Pending"), but original hustoj works fine ("Accepted"). Should I edit /home/judge/etc/judge.conf, or should I edit other configuration files?

**Comment by freefcw** [comment]
@kaichengyan the newer version is compatible with original hustoj, the judge server is the same.You should test judge server
