### ISSUE TITLE
APPPATH/classes/OJ.php [ 10 ]

### ISSUE THREAD

**Issue by Bahodir94** [freefcw/hustoj#57]
I have problem!!!

**Comment by Bahodir94** [comment]
ErrorException [ Parse Error ]: syntax error, unexpected '['

APPPATH/classes/OJ.php [ 10 ]

 5 {
 6     const per_page = 50;
 7     /**
 8      * @var array result code to human language short
 9      */
10     public static $result = [
11         '4' => 'AC',
12         '5' => 'PE',
13         '6' => 'WA',
14         '7' => 'TLE',
15         '8' => 'MLE',

    {PHP internal call} » Kohana_Core::shutdown_handler()

**Comment by freefcw** [comment]
please support your php version and more information

**Comment by Bahodir94** [comment]
thanks it work!!!
